[package]
name = "memory-rs"
version = "0.1.2"
authors = ["Sebastian"]
edition = "2018"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["winuser", "tlhelp32", "handleapi", "impl-default", "memoryapi", "processthreadsapi", "psapi", "libloaderapi"] }
anyhow = "1.0.34"
